import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CalendarDays, Clock } from "lucide-react";
import { articles, getArticle } from "../articles";

type PageProps={params:Promise<{slug:string}>};

export function generateStaticParams(){return articles.map(article=>({slug:article.slug}))}

export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{slug}=await params;const article=getArticle(slug);if(!article)return{};return{title:`${article.title} | BizPilot AI`,description:article.description,alternates:{canonical:`/blog/${article.slug}`},openGraph:{title:article.title,description:article.description,type:"article",url:`/blog/${article.slug}`,publishedTime:article.publishedAt,images:[]},twitter:{card:"summary",title:article.title,description:article.description,images:[]}}}

function Mark(){return <span className="blog-logo-mark"><svg viewBox="0 0 64 64" aria-hidden="true"><path d="M17 14h17c10 0 16 5 16 13 0 5-3 9-8 11 7 2 10 6 10 12 0 9-7 14-18 14H17V14Zm10 9v11h7c5 0 8-2 8-6s-3-5-8-5h-7Zm0 19v13h8c6 0 9-2 9-6s-3-7-9-7h-8Z" fill="currentColor"/><path d="m38 19 8-8 8 8M46 11v17" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/></svg></span>}

export default async function ArticlePage({params}:PageProps){const{slug}=await params;const article=getArticle(slug);if(!article)notFound();const related=articles.filter(item=>item.slug!==article.slug).slice(0,2);const schema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.publishedAt,author:{"@type":"Organization",name:"BizPilot AI"},publisher:{"@type":"Organization",name:"BizPilot AI"},mainEntityOfPage:`https://bizpilot-ai.oiotitus333.chatgpt.site/blog/${article.slug}`};return <main className="blog-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="blog-nav"><div className="page-width"><Link className="blog-brand" href="/"><Mark/><span>BizPilot <b>AI</b></span></Link><nav><Link href="/">Home</Link><Link className="blog-nav-active" href="/blog">Blog</Link><Link className="button button-dark" href="/">Open BizPilot <ArrowRight size={15}/></Link></nav></div></header><article className="article-wrap"><Link className="article-back" href="/blog"><ArrowLeft/> All guides</Link><header className="article-header"><span className="blog-category">{article.category}</span><h1>{article.title}</h1><p>{article.description}</p><div><span><CalendarDays/> {new Date(`${article.publishedAt}T00:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</span><span><Clock/> {article.readingTime}</span></div></header><div className="article-body"><p className="article-intro">{article.intro}</p>{article.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.bullets&&<ul>{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>}</section>)}<aside className="article-note"><b>Use this guide as a starting point.</b><p>Adapt each recommendation to your business, verify important facts and obtain professional advice where necessary.</p></aside></div></article><section className="related-guides page-width"><span className="eyebrow">Continue learning</span><h2>Related BizPilot guides</h2><div>{related.map(item=><article key={item.slug}><span className="blog-category">{item.category}</span><h3><Link href={`/blog/${item.slug}`}>{item.title}</Link></h3><p>{item.description}</p><Link href={`/blog/${item.slug}`}>Read guide <ArrowRight/></Link></article>)}</div></section><footer className="blog-footer"><div className="page-width"><Link className="blog-brand" href="/"><Mark/><span>BizPilot <b>AI</b></span></Link><p>Run your business smarter.</p><nav><Link href="/">Home</Link><Link href="/blog">Blog</Link></nav><small>© 2026 BizPilot AI</small></div></footer></main>}
